export const REQUESTED_ARTICLES = 'REQUESTED_ARTICLES';
export const RECIEVED_ARTICLES = 'RECIEVED_ARTICLES';

export const ADDED_ARTICLE = 'ADDED_ARTICLE';
export const ERROR_ADDING_ARTICLE = 'ERROR_ADDING_ARTICLE';

export const EDITED_ARTICLE = 'EDITED_ARTICLE';
export const ERROR_EDITING_ARTICLE = 'ERROR_EDITING_ARTICLE';
